language: d
d:
  - dmd
  - ldc
branches:
  only:
    - master
addons:
  apt:
    packages:
    - libevent-dev
script:
  - git clone https://github.com/stonemaster/dlang-tour ../tour
  - mkdir -p ../tour/public/content/lang
  - mv * ../tour/public/content/lang
  - wget https://raw.githubusercontent.com/dlang/tools/master/rdmd.d
  - ${DC} rdmd.d
  - export PATH=$PATH:$PWD
  - (cd ../tour && dub --compiler=${DC} -- --sanitycheck .)
