dist: trusty
language: d
d:
  - dmd
  - ldc
branches:
  only:
    - master
addons:
  apt:
    packages:
    - libevent-dev

script:
  - echo "Check for trailing whitespace"
  - grep -nr --include \*.md '\s$' . ; test $? -eq 1
  - echo "Check for tabs"
  - grep -nrP --include \*.md '\t' . ; test $? -eq 1
  - git clone https://github.com/dlang-tour/core ../tour
  - mkdir -p ../tour/public/content/lang
  - mv * ../tour/public/content/lang
  - wget https://raw.githubusercontent.com/dlang/tools/master/rdmd.d
  - ${DC} rdmd.d
  - export PATH=$PATH:$PWD
  - (cd ../tour && dub --compiler=${DC} -- --sanitycheck .)
